spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/djuric-ivan/config-repo
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/


server:
  port: 9595

microservice:
  payment-service:
    endpoints:
      fetchPaymentById:
        uri: http://PAYMENT-SERVICE/payments/
  user-service:
    endpoints:
      fetchUserById:
        uri: http://USER-SERVICE/users/

test:
  input: 1
